export const APP_URL_DEV = "";

export const categories = [
  { id: "BUSINESS_AND_ECONOMICS", label: "Biznes i ekonomia", icon: "work" },
  { id: "EDUCATION", label: "Edukacja", icon: "school" },
  { id: "ENGINEERING", label: "Inynieria", icon: "settings" },
  { id: "MEDICINE", label: "Medycyna", icon: "stethoscope" },
  { id: "NATURAL", label: "Przyroda", icon: "psychiatry" },
  { id: "HUMANISTIC", label: "Nauki humanistyczne", icon: "neurology" },
  { id: "SOCIAL", label: "Nauki społeczne", icon: "group" },
  { id: "SCIENCE", label: "Nauki ścisłe", icon: "science" },
  { id: "ARTS", label: "Sztuka i kultura", icon: "palette" },
  { id: "INFORMATION", label: "Technologie Informacyjne", icon: "computer" },
];

export const defaultFilters = {
  stationary: true,
  universityType: ["PUBLIC"],
};

export const filterStructure = [
  {
    id: "universityType",
    label: "Typ uczelnii",
    type: "select",
    options: [
      { label: "Publiczna", value: "PUBLIC" },
      { label: "Prywatna", value: "PRIVATE" },
    ],
  },
  {
    id: "level",
    label: "Poziom studiów",
    type: "select",
    options: [
      { label: "I stopnia (inżynierskie)", value: "1inz" },
      { label: "I stopnia (licencjackie)", value: "1lic" },
      { label: "II stopnia", value: "2" },
      { label: "Jednoliste magisterskie", value: "2jednolite" },
    ],
  },
  {
    id: "finalsSubjects",
    label: "Przedmioty maturalne",
    type: "select",
    options: [
      { label: "matematyka", value: "matematyka" },
      { label: "język polski", value: "język polski" },
      { label: "język obcy nowożytny", value: "język obcy nowożytny" },
      { label: "biologia", value: "biologia" },
      { label: "chemia", value: "chemia" },
      { label: "filozofia", value: "filozofia" },
      { label: "fizyka", value: "fizyka" },
      { label: "geografia", value: "geografia" },
      { label: "historia", value: "historia" },
      { label: "historia muzyki", value: "historia muzyki" },
      { label: "historia sztuki", value: "historia sztuki" },
      { label: "informatyka", value: "informatyka" },
      {
        label: "język łaciński i kultura antyczna",
        value: "język łaciński i kultura antyczna",
      },
      { label: "wiedza o społeczeństwie", value: "wiedza o społeczeństwie" },
    ],
  },
  {
    id: "interests",
    label: "Zainteresowania",
    type: "select",
    options: [
      {label: "Programowanie", value: "Programowanie"},
      {label: "Analiza Danych", value:     "Analiza Danych"},
      {label: "Energia Odnawialna", value:     "Energia Odnawialna"},
      {label: "Projektowanie Elektroniki", value:     "Projektowanie Elektroniki"},
      {label: "Inżynieria Samochodowa", value:     "Inżynieria Samochodowa"},
      {label: "Robotyka", value:     "Robotyka"},
      {label: "Operacje Górnicze", value:     "Operacje Górnicze"},
      {label: "Zrównoważone Zarządzanie Zasobami", value:     "Zrównoważone Zarządzanie Zasobami"},
      {label: "Modelowanie Matematyczne", value:     "Modelowanie Matematyczne"},
      {label: "Analiza Numeryczna", value:     "Analiza Numeryczna"},
      {label: "Fizyka Teoretyczna", value:     "Fizyka Teoretyczna"},
      {label: "Fizyka Eksperymentalna", value:     "Fizyka Eksperymentalna"},
      {label: "Badania Medyczne", value:     "Badania Medyczne"},
      {label: "Opieka Nad Pacjentem", value:     "Opieka Nad Pacjentem"},
      {label: "Projektowanie Sprzętu", value:     "Projektowanie Sprzętu"},
      {label: "Zastosowania Biomedyczne", value:     "Zastosowania Biomedyczne"},
      {label: "Biotechnologia Środowiskowa", value:     "Biotechnologia Środowiskowa"},
      {label: "Studia Środowiskowe", value:     "Studia Środowiskowe"},
      {label: "Planowanie Przestrzenne", value:     "Planowanie Przestrzenne"},
      {label: "Polityka Gospodarcza", value:     "Polityka Gospodarcza"},
      {label: "Analiza Finansowa", value:     "Analiza Finansowa"},
      {label: "Przywództwo", value:     "Przywództwo"},
      {label: "Strategia Biznesowa", value:     "Strategia Biznesowa"},
      {label: "Globalny Marketing", value:     "Globalny Marketing"},
      {label: "Międzynarodowe Finanse", value:     "Międzynarodowe Finanse"},
      {label: "Zarządzanie Międzykulturowe", value:     "Zarządzanie Międzykulturowe"},
      {label: "Planowanie Finansowe", value:     "Planowanie Finansowe"},
      {label: "Finanse Korporacyjne", value:     "Finanse Korporacyjne"},
      {label: "Governance IT", value: "Governance IT"}
    ],
  },,
  {
    id: "occupations",
    label: "Zawód po studiach",
    type: "select",
    options: [
      {label: "Programista", value: "Programista"},
      {label: "Analityk Danych", value: "Analityk Danych"},
      {label: "Inżynier Oprogramowania", value: "Inżynier Oprogramowania"},
      {label: "Inżynier Elektroniki", value: "Inżynier Elektroniki"},
      {label: "Projektant Układów Elektronicznych", value: "Projektant Układów Elektronicznych"},
      {label: "Inżynier Mechanik", value: "Inżynier Mechanik"},
      {label: "Projektant Maszyn", value: "Projektant Maszyn"},
      {label: "Inżynier Górnik", value: "Inżynier Górnik"},
      {label: "Specjalista ds. Zrównoważonego Rozwoju", value: "Specjalista ds. Zrównoważonego Rozwoju"},
      {label: "Analityk Matematyczny", value: "Analityk Matematyczny"},
      {label: "Specjalista ds. Analizy Numerycznej", value: "Specjalista ds. Analizy Numerycznej"},
      {label: "Badacz Fizyczny", value: "Badacz Fizyczny"},
      {label: "Nauczyciel Akademicki", value: "Nauczyciel Akademicki"},
      {label: "Lekarz", value: "Lekarz"},
      {label: "Specjalista ds. Badań Medycznych", value: "Specjalista ds. Badań Medycznych"},
      {label: "Inżynier Komputerowy", value: "Inżynier Komputerowy"},
      {label: "Programista Sprzętu", value: "Programista Sprzętu"},
      {label: "Biotechnolog", value: "Biotechnolog"},
      {label: "Specjalista ds. Badań Biomedycznych", value: "Specjalista ds. Badań Biomedycznych"},
      {label: "Geograf", value: "Geograf"},
      {label: "Urbanista", value: "Urbanista"},
      {label: "Ekonomista", value: "Ekonomista"},
      {label: "Analityk Finansowy", value: "Analityk Finansowy"},
      {label: "Konsultant ds. Polityki Gospodarczej", value: "Konsultant ds. Polityki Gospodarczej"},
      {label: "Manager", value: "Manager"},
      {label: "Specjalista ds. Zarządzania Zasobami Ludzkimi", value: "Specjalista ds. Zarządzania Zasobami Ludzkimi"},
      {label: "Specjalista ds. Międzynarodowych Stosunków Gospodarczych", value: "Specjalista ds. Międzynarodowych Stosunków Gospodarczych"},
      {label: "Dyplomata", value: "Dyplomata"},
      {label: "Księgowy", value: "Księgowy"},
      {label: "Controller Finansowy", value: "Controller Finansowy"},
      {label: "Specjalista ds. Informatyki Zarządczej", value: "Specjalista ds. Informatyki Zarządczej"},
      {label: "Analityk Biznesowy", value: "Analityk Biznesowy"}
    ],
  },
];

export const results = [
  {
    id: 0,
    imageUrl:
      "https://images.unsplash.com/20/cambridge.JPG?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3494&q=80",
    name: "Politechnika Śląska",
    location: "Katowice",
  },
  {
    id: 1,
    imageUrl:
      "https://images.unsplash.com/photo-1581362072978-14998d01fdaa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2756&q=80",
    name: "Akademia Górniczo-Hutnicza",
    location: "Kraków",
  },
  {
    id: 2,
    imageUrl:
      "https://images.unsplash.com/photo-1591123120675-6f7f1aae0e5b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=3538&q=80",
    name: "Uniwersytet Jagielloński",
    location: "Kraków",
  },
];
